const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: '.env.local' });

const swContent = `// Firebase Cloud Messaging Service Worker
// This file is generated by scripts/generate-sw.js
// Do not edit directly

importScripts('https://www.gstatic.com/firebasejs/10.7.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.0/firebase-messaging-compat.js');

firebase.initializeApp({
    apiKey: "${process.env.NEXT_PUBLIC_FIREBASE_API_KEY}",
    authDomain: "${process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}",
    projectId: "${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}",
    storageBucket: "${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${process.env.NEXT_PUBLIC_FIREBASE_APP_ID}",
});

const messaging = firebase.messaging();

// Handle background messages
messaging.onBackgroundMessage((payload) => {
    console.log('Received background message:', payload);

    const notificationTitle = payload.notification?.title || 'AFCON 2025 Update';
    const notificationOptions = {
        body: payload.notification?.body || 'New update available',
        icon: '/afcon-logo.png',
        badge: '/afcon-badge.png',
        tag: payload.data?.fixtureId || 'afcon-notification',
        data: payload.data,
        vibrate: [200, 100, 200],
        actions: [
            { action: 'open', title: 'View Match' },
            { action: 'dismiss', title: 'Dismiss' }
        ]
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    if (event.action === 'dismiss') return;

    const fixtureId = event.notification.data?.fixtureId;
    const url = fixtureId
        ? \`/afcon25/fixtures/\${fixtureId}\`
        : '/afcon25/fixtures';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true })
            .then((clientList) => {
                // Focus existing window if available
                for (const client of clientList) {
                    if (client.url.includes('/afcon25') && 'focus' in client) {
                        return client.focus();
                    }
                }
                // Open new window
                if (clients.openWindow) {
                    return clients.openWindow(url);
                }
            })
    );
});
`;

fs.writeFileSync(path.join(__dirname, '../public/firebase-messaging-sw.js'), swContent);
console.log('Generated public/firebase-messaging-sw.js');
